name: CI

on:
  push:
    tags:
      - "*.*.*"

jobs:

  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check that the tag is included in a protected branch
        # This is a security check: commits in protected branches have been reviewed.
        # While anyone can push a tag, if we only allow tags in protected branches,
        # we can be sure that the code the tag points to has been reviewed.
        run: |
          if git merge-base --is-ancestor tags/${TAG} remotes/origin/main; then
            exit 0
          fi

          # Check all hotfix branches
          for branch in $(git branch -r --list 'origin/hotfix/*'); do
            if git merge-base --is-ancestor tags/${TAG} $branch; then
              exit 0
            fi
          done
        env:
          TAG: ${{ github.ref_name }}
