name: CI

on:
  push:
    tags:
      - "*.*.*"

jobs:

  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check that the tag is included in a protected branch
        # This is a security check: commits in protected branches have been reviewed.
        # While anyone can push a tag, if we only allow tags in protected branches,
        # we can be sure that the code the tag points to has been reviewed.
        run: |
          git fetch --depth=1 origin '+refs/heads/main:refs/remotes/origin/main'
          git fetch --depth=1 origin '+refs/heads/hotfix/*:refs/remotes/origin/hotfix/*'
          # `git branch ...` will either return an empty string or a list of branches that contain the tag.
          # The `| grep "[[:alnum:]]"` at the end turns [non-empty or empty stdout] into (0 or 1 return code)
          if ! git branch --contains tags/${TAG} --format '%(refname:short)' --list 'main' 'hotfix/*' | grep "[[:alnum:]]"; then
            echo "Tag is not included in a protected branch. Not building the Docker image for security reasons."
            exit 1
          fi
        env:
          TAG: ${{ github.ref_name }}
